<?php
$pageTitle = 'Our Heritage — The Story of SENA';
$pageDescription = 'Discover the SENA legacy: a tribute to conviction, honour and Malaysian assembly heritage, founded by Pathman Senathirajah.';
$activePage = 'heritage';
require __DIR__ . '/app/partials/header.php';
?>
<main id="main" class="inner-page">
    <section class="inner-hero heritage-hero"><div><p class="eyebrow">OUR HERITAGE</p><h1>A name.<br>A promise.<br>A legacy.</h1><p>When you wear a SENA timepiece, you carry more than an instrument of time—you hold a story of passion, perseverance, and legacy.</p></div><img src="assets/optimized/lifestyle.webp" alt="A SENA watch worn in everyday life" width="800" height="800"></section>
    <section class="inner-section story-grid"><div><p class="eyebrow">THE STORY OF SENA</p><h2>Built to be worn.<br>Meant to be<br>handed down.</h2></div><div class="prose"><p>SENA was born to ensure that the art of classic watchmaking remains vibrant for future generations. While smart tech surrounds us, SENA stands for something permanent: a reliable, practical tool watch that simply tells time and date with quiet confidence. It’s built to be grabbed as reflexively as your car keys before stepping out to face the world.</p><p>Derived from SENA, the name of Founder Pathman Senathirajah’s father, this brand carries the title of a warrior-general, an unyielding tribute to conviction, honour, and purpose.</p><p>Born of a journey of perseverance and pride, each watch embodies a son’s promise to honour his father’s name—proving that a true legacy isn’t meant to be locked away but worn, lived, and handed down.</p></div></section>
    <section class="heritage-quote"><blockquote>“A true legacy isn’t meant to be locked away—it is built to be worn, lived in, and passed down through generations.”</blockquote></section>
    <section class="inner-section story-grid"><img class="story-image" src="assets/optimized/packaging.webp" alt="SENA watch and presentation box" width="800" height="700" loading="lazy"><div class="prose"><p class="eyebrow">ASSEMBLED IN MALAYSIA</p><h2>Local pride.<br>Lasting purpose.</h2><p>More than a watch, SENA marks a historic milestone as one of the few watches assembled in Malaysia. Every timepiece stands as a monument to local assembly heritage and craftsmanship, proving that world-class horology belongs right here.</p><p>We assemble our watches in measured, dedicated batches to ensure that every unit undergoes strict quality checks and pressure testing to meet our 5 ATM standard.</p><p>Designed without aristocratic pretence or luxury inflation, every SENA watch is focused purely on absolute clarity, time, date, and quiet confidence.</p><a class="text-link" href="specifications.php">Discover the craftsmanship ↗</a></div></section>
    <section class="chief-story" aria-labelledby="heritage-chief-title"><div class="chief-video"><iframe src="https://www.youtube-nocookie.com/embed/6ym0e4vxdwA" title="A message from SENA’s Chief" width="960" height="540" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div><div class="chief-copy"><p class="eyebrow">THE VISION BEHIND SENA</p><h2 id="heritage-chief-title">A message from our Chief</h2><p>“We built SENA for the new generation—from young hustlers to seasoned collectors—to prove that world-class horology belongs right here.”</p><a class="text-link" href="https://www.youtube.com/watch?v=6ym0e4vxdwA" target="_blank" rel="noopener noreferrer">Watch on YouTube ↗</a></div></section>
    <section class="inner-banner"><p class="eyebrow">THE WARISAN COLLECTION</p><h2>Carry the story forward.</h2><p>SENA is a watch made for everyday life—practical, sturdy, and ready for wherever your path leads.</p><a class="outline-button" href="warisan.php">Explore timepieces ↗</a></section>
</main>
<?php require __DIR__ . '/app/partials/footer.php'; ?>
