<?php
require_once __DIR__ . '/app/bootstrap.php';
$pageTitle = 'Specifications & Craftsmanship — SENA Watches';
$pageDescription = 'Compare Warisan watch movements, case dimensions, materials and features. Japanese Miyota quartz, 316L steel, sapphire crystal and 5 ATM water resistance.';
$activePage = 'specifications';
require __DIR__ . '/app/partials/header.php';
?>
<main id="main" class="inner-page">
    <section class="inner-title"><p class="eyebrow">CRAFTSMANSHIP &amp; ENGINEERING</p><h1>Built without<br>compromise.</h1><p>Real horology is defined by pure utility, unyielding purpose, and local pride. Every detail is engineered for daily life.</p></section>
    <section class="inner-section material-grid"><article><span class="detail-number">01</span><h2>316L stainless steel</h2><p>Corrosion-resistant steel forms the case, crown and buckle, bringing everyday durability to a purposeful design.</p></article><article><span class="detail-number">02</span><h2>Sapphire crystal</h2><p>Scratch-resistant sapphire with an inner anti-reflective coating protects the dial and supports clear readability.</p></article><article><span class="detail-number">03</span><h2>Japanese precision</h2><p>Miyota quartz movements power the three-hand date, chronograph and multi-function models in the Warisan collection.</p></article><article><span class="detail-number">04</span><h2>Low-light legibility</h2><p>Swiss New-Lite C1 luminous detailing on the brass base dial and hands brings clarity after daylight fades.</p></article><article><span class="detail-number">05</span><h2>Quick-release straps</h2><p>Matching leather and high-density canvas straps let you switch between everyday settings without tools.</p></article><article><span class="detail-number">06</span><h2>5 ATM water rating</h2><p>Rated to 5 ATM / 50 metres. Each timepiece undergoes quality checks and pressure testing during assembly.</p></article></section>
    <section class="inner-section comparison-section"><div class="section-heading"><div><p class="eyebrow">THE WARISAN COLLECTION</p><h2>Compare the details.</h2></div><p>Choose the size and functions<br>that fit your everyday life.</p></div><p class="table-hint">Scroll across to compare all four models.</p><div class="comparison-scroll" tabindex="0" role="region" aria-label="Warisan specifications comparison"><table class="comparison-table"><caption class="sr-only">Warisan quartz collection specifications</caption><thead><tr><th scope="col">Specification</th><?php foreach ($senaFamilies as $id=>$family): ?><th scope="col"><a href="product.php?product=<?= senaEscape($id) ?>-green"><?= senaEscape($family['name']) ?><small><?= senaEscape($family['edition']) ?></small></a></th><?php endforeach; ?></tr></thead><tbody>
    <?php foreach (['reference'=>'Model reference','movement'=>'Japanese quartz movement','size'=>'Case dimensions','function'=>'Functions','strap'=>'Strap width'] as $key=>$label): ?><tr><th scope="row"><?= senaEscape($label) ?></th><?php foreach ($senaFamilies as $family): ?><td><?= senaEscape($family[$key]) ?></td><?php endforeach; ?></tr><?php endforeach; ?>
    <?php foreach (['Case, crown & buckle'=>'316L stainless steel','Crystal'=>'Sapphire with inner AR coating','Case back'=>'316L steel with super-hardened mineral glass and logo','Bezel'=>'Uni-directional steel with aluminium ring','Water resistance'=>'5 ATM / 50 metres / 165 feet','Straps included'=>'Matching leather and canvas, quick-release spring bars','Warranty'=>'2-year international warranty'] as $label=>$value): ?><tr><th scope="row"><?= senaEscape($label) ?></th><td colspan="4"><?= senaEscape($value) ?></td></tr><?php endforeach; ?>
    </tbody></table></div></section>
    <section class="inner-banner"><p class="eyebrow">VERSATILITY AT YOUR FINGERTIPS</p><h2>One watch. Your every day.</h2><p>Transition between leather and canvas with the integrated quick-release strap system.</p><a class="outline-button" href="owners-guide.php#straps">Explore the owner’s guide ↗</a></section>
</main>
<?php require __DIR__ . '/app/partials/footer.php'; ?>
